/**
 * Metro library's built-in icon enumeration.
 */
export type Icon =
  | "bullet"
  | "checked"
  | "arrowLeft"
  | "arrowRight"
  | "arrowUp"
  | "arrowDown"
  | "fullArrowLeft"
  | "fullArrowRight"
  | "fullArrowUp"
  | "fullArrowDown"
  | "search"
  | "clear"
  | "games"
  | "internetExplorer"
  | "video"
  | "store"
  | "settings"
  | "mail"
  | "user"
  | "security"
  | "calculator"
  | "camera"
  | "bluetooth"
  | "news"
  | "bing"
  | "opera"
  | "chrome"
  | "firefox"
  | "msedge"
  | "lapis"
  | "idea"
  | "help"
  | "helpCircle"
  | "new"
  | "trash"
  | "hamburguerMenu"
  | "shutdown"
  | "power"
  | "seen"
  | "openEnvelope"
  | "markAsRead"
  | "notificationEnvelope"
  | "markAsUnread"
  | "starOutline"
  | "starFill"
  | "terminal";

export function Icon(self: Icon): Icon {
  return self;
}